### ISSUE TITLE
Dead kernel when trying to compute stats

### ISSUE THREAD

**Issue by lucabaldassarre** [ozak/georasters#25]
I have a GeoPandas dataFrame, named `selection`, which I want to use to compute stats over a georaster, named `data`.
When I try this command, the kernel dies, without giving any error:

`means = data.stats(selection, stats = 'mean')`

Any idea of where the problem might be?

I'm using python 3.6.4 and georasters 0.5.8.

**Comment by ozak** [comment]
I'm not sure. I haven't tested ``georasters`` on ``3.6``, but in principle it should not create any issues. Can you test in ``3.5``? Or share your data so I can test it? 

Also, make sure all geometries are valid,  since that may cause issues. It is strange that you do not get any specific error for the kernel dying. How big is the data?

**Comment by lucabaldassarre** [comment]
I opened another issue related to the bounds of the raster. Perhaps that is connected to the dying kernel.

**Comment by ozak** [comment]
I think the method is written for rasters with one band. So that could be one issue. Can you try with only one band? I'll try to generalize the import so one can select the band. Not sure it makes sense to import all of them for the methods that are implemented here. But I could be wrong...I never use multi-band rasters.

**Comment by lucabaldassarre** [comment]
When using a one-band raster the method does not kill the kernel, but returns the following error:

```
~/.conda/envs/geo/lib/python3.6/site-packages/georasters/georasters.py in stats(self, shp, stats, add_stats, raster_out, *args, **kwargs)
    738                                                                   projection=self.projection,
    739                                                                   datatype=self.datatype))
--> 740         statcols = list(set([i for i in df.properties[0].iterkeys()]).difference(set(shp.columns)))
    741         cols = shp.columns.tolist()+statcols
    742         cols = [i for i in cols if i != 'geometry' and i.find('mini_raster') == -1]

AttributeError: 'dict' object has no attribute 'iterkeys'
```

However if I use `rasterstats`, I get a proper output:

```
import rasterstats as rs
statistics = rs.zonal_stats(selection, raster, stats = 'mean')
```

where `raster` is the path to the raster I'm loading.

**Comment by ozak** [comment]
Ok...I think I found the issue. It was not passing the ``stats`` variable to ``zonal_stats``. Additionally, there was a change in the ``dict`` iterator between ``py2`` and ``py3`` which caused the issue. I have updated this and the issue should be solved in the latest version, which is already up.

**Comment by lucabaldassarre** [comment]
I still have the dictionary issue with the new version 0.5.9.
